### ISSUE TITLE
Add Air Quality Cluster Definition

### ISSUE THREAD

**Issue by p0fi** [project-chip/connectedhomeip#26194]
# 📖 Description
To add full support for the Air Quality Cluster to the SDK a cluster definition needs to be added. 

## 🔎 Details
A cluster definition is an xml file which describes the cluster according to the spec.

## ✅ Tasks 
- [x] Create `<cluster-name>-cluster.xml` under `src/app/zap-templates/zcl/data-model/chip`
- [x] Add file reference to `.github/workflows/tests.yaml`
- [x] Add file reference to `scripts/rules.matterlint`
- [x] Add file reference to `src/app/zap-templates/zcl/data-model/all.xml`
- [x] Add file reference to `src/app/zap-templates/zcl/zcl-with-test-extensions.json`
- [x] Add file reference to `src/app/zap-templates/zcl/zcl.json`
- [x] Enable new cluster to the Darwin and Android clients (`controller-clusters.zap`)
- [x] Add all new clusters to `src/app/zap_cluster_list.json`
- [x] Run `./scripts/tools/zap_regen_all.py`

## 🔗 Links/References
- [Wiki from Petru on how to add a new device type](https://groups.csa-iot.org/wg/matter-tsg/wiki/howto-add-a-new-device-type)
