### ISSUE TITLE
Update Fan Control Cluster Definition

### ISSUE THREAD

**Issue by p0fi** [project-chip/connectedhomeip#26224]
# 📖 Description
The fan control cluster definition needs to be updated with the changes from the air quality spec update.

## 🔎 Details
The cluster definition is an xml file which describes the cluster according to the spec and is found [here](https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/fan-control-cluster.xml).

## ✅ Tasks 
- [ ] Add Direction and AirflowDirection enums
- [ ] Add AirflowDirection attribute
- [ ] Add Step command
- [ ] Rebuild chip-tool and test command
