### ISSUE TITLE
Update Fan Control Server Code

### ISSUE THREAD

**Issue by mhazley** [project-chip/connectedhomeip#26258]
# 📖 Description
The Fan Control server code needs to be updated to include support for the updates to the cluster additions and to also complete all functionality from the original spec.

## 🔎 Details
The[ Fan Control server code](https://github.com/project-chip/connectedhomeip/tree/master/src/app/clusters/fan-control-server) is about 70% complete as per the original spec and there have been new additions from #26224 that add a new attribute, two new features and a command. The entire cluster needs to be updated to spec so it can be testable.

## ✅ Tasks 
- [ ] Add feature map checking in pre callback for speed setting
- [ ] Add feature map checking in pre callback for wind setting
- [ ] Add feature map checking in pre callback for rock setting
- [ ] Add feature map checking in pre callback for airflow direction setting
- [ ] Remove server code where setting attribute updates current attribute automatically
- [ ] Add support for Step Command
  - [ ] Check feature map for speed & step conformance
  - [ ] Update speed setting accordingly
