### ISSUE TITLE
Add delegate to Fan Control to support application specific Step Command

### ISSUE THREAD

**Issue by mhazley** [project-chip/connectedhomeip#27328]
### Description

The Fan Control cluster has added a `Step` command and the effect of that command is manufacturer specific. 

Therefore, we need to add a delegate to the Fan Control cluster in SDK so that the application can configure an object to handle this command. 

### TODO

- [x] Add delegate table to Fan Control server
- [x] Add function for application to assign delegates to endpoints
- [x] Add delegate header with virtual function, `HandleStep`
- [x] Add instance of this delegate to the existing fan stub in all clusters
