### ISSUE TITLE
[1.2] Time sync - tracking 

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#27575]
### Reproduction steps

PR inspection

### Bug prevalence

always

### GitHub hash of the SDK that was being used

abb7a802231f2b615b3030c5df43f5144871e09c

### Platform

core

### Type

Common Cluster Logic

### Anything else?

- [ ]  Figure out what happens if the TZ offset is out of range AND the code fails to load a time zone. See https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1240951613. In particular, which error code needs to be returned (I think this still needs to be a constraint error), AND can we do this check in a way that prevents making changes that necessitate reloading the time
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1240951626 - align errors between the ember command parser and the
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1212444174 - better overflow protection when going from chip epoch to unix epoch
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1247927627 - handlers for 3.5.6.1 SHOULD - If a Node has used the Last Known Good UTC Time, it SHOULD recheck its security materials and existing connections if it later achieves time synchronization.
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242621779 - time zone name copying
- [ ] document event generation on time zone name only change. https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242626060
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242627777 - change event flag from parameter to return
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242630331 - change size comparison
- [ ] follow up on ScheduleDelayedAction function https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242638706
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242689236 - adjust TZ / DST list on time change
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242639975 - propagate error for set or document why the error changes
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1241153735 - tighten up time get / set features to move them closer to the receive / send boundary
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242642964 - remove casts on TZ / DST offset
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242655854 - refactor DST list parsing code
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242657708 - remove mEventFlag
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242658973 - minor code suggestion from Boris
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242660231 - don't encode local time on error
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242667611 , https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242668186 use unknown value check for enums
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242673209 - double check error code for invalid enum
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242671601 - tighten up granularity check
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242676471 - fix how we're setting granularity
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242683543 - move event generation into the instance rather than handling in the ember functions
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1240968943 - fix time source check to allow domain name addresses
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242685200 - move the IP / domain address checks out of the delegate - this is not something the app needs to care about.
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1241227274 - adjust revision in the lighting app example
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242680899 - rename GetUpdatedTimeZoneState to UpdateTimeZoneState
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242684936 - remove NTPDomain check from delegate - this should be an SDK decision
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242550991 - remove mEndpoint - time sync is now mandated to be only on EP0 per the spec (also https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242569896)
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242547766 - document expected size of the buffer for time zone.
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242548121 - document expected size of the buffer for DST
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242545328 - document expected size of buffer for default NTP
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242607150 - static assertion that the name sizes match between the storage and incoming
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242608673 - document where the 64 for time zone name comes from (spec ref)
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082/files#r1242613876 - fix size comparison
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242628037 - document or fix event generation when going into or out of invalid TZ state
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242628882 - initialize CharSpan using array form
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242631916 - fix error codes on dstoffset
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242634295 - consider refactoring LoadDSTOffset and LoadTimeZone out of SetDSTOffset / SetTimeZoneOffset to reduce the number of call sites
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242635346 - factor out duplicated logic in LoadTimeZone
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242650472 - document or fix size change on tzList
- [ ] https://github.com/project-chip/connectedhomeip/pull/26082#discussion_r1242668186 - minor code change

**Comment by cecille** [comment]
Woah - why was this closed?

**Comment by fessehaeve** [comment]
Thanks @cecille for the catch. I have started working on some of these already.
