### ISSUE TITLE
[refactor] Make CommandHandlerInterface registration consistent with AttributeAccessInterface

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#34258]
AttributeAccessInterface uses a `AttributeAccessInterfaceRegistry.h` for register/unregister which provides decoupling of registrations.

CommandHandlerInterface instead has register/unregister/find directly in InteractionModelEngine, which makes the InteractionModelEngine a larger and more complex object.

There is a benefit to tie this to IME in that several IME can work in parallel with different setups, however once we have a data model split working, the data model can decide how to route both AAI and CHI. In that case a consistent way of handling both seems desirable and a separate `registry` seems better (allow the IME to be simplified).

#### TODO items

- [x] Create a `CommandHandlerInterfaceRegistry` similar to AttributeAccessInterfaceRegistry
- [x] Create `@deprecated` redirects in InteractionModelEngine for one version backwards compatibility hooks
- [x] Make use of this new CHI Registry directly into DataModel implementations (like codegen or others)
