### ISSUE TITLE
Review comments for WriteClient/Handler PR

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#7795]
#### Problem
Various issues in #7730 that were not caught in review:
* [x] Docs for `InteractionModelDelegate::WriteResponsStatus` have "an Write Response" instead of "a Write Response"
* [x] `aCommandIndex` argument name for `InteractionModelDelegate::WriteResponseStatus` makes no sense.
* [x] `aCommandIndex` argument for `InteractionModelDelegate::WriteResponseStatus` is not documented; I have no idea what I'd do with it as an API consumer.
* [x] Documentation for `InteractionModelDelegate::WriteResponseProcessed` says "already" which sounds like "it's been done once, so there's nothing we need to do", and I am pretty sure that is not the intent of this callback.
* [x] Documentation for `InteractionModelDelegate::WriteResponseProtocolError` has "an Write Response"
* [x] Documetation for `InteractionModelDelegate::WriteResponseError` talks about `aCWRiteClient`, whatever that is.
* [ ]  InteractionModelEngine::OnWriteRequest aborts exchange contexts if a handler cannot be found. An abort will fail to send an MRP ack; this does not seem like the right behavior.  Tracked in #7968
* [x] Documentation for `InteractionModelEngine::NewWriteClient` says "use to send do a write".  "send", or "do", not both, please.
* [x] Documentation for `InteractionModelEngine::NewWriteClient` says consumer is responsible for calling `Shutdown`, but `WriteClient::OnMessageReceived` shuts itself down.  This seems like copy/paste from `ReadClient`, which does _NOT_ call `Shutdown` itself, ever.
* [x] Documentation for `InteractionModelEngine::NewWriteClient` says `CHIP_ERROR_INCORRECT_STATE` is returned when no write client is available, but the implementation returns `CHIP_ERROR_NO_MEMORY`.
* [x] Comments inside `WriteClient::ClearExistingExchangeContext` talk about "one Echo exchange", which makes no sense.
* [ ] There are `Abort`s of exchange contexts in various places in the PR. There probably should not be any at all. I suspect that little to no testing was done of how all these Aborts interact with the intended MRP semantics in various error conditions, and am quite sure they interact badly.  Tracked in #7969
* [x] In `WriteClient::SendWriteRequest` there's a "TODO: temprary create ..." comment which is clearly copy/pasted from somewhere, complete with multiple grammar issues.
* [x] `WriteClient::SendWriteRequest` sets `kNoAutoRequestAck`  for some reason.  It should not be doing that. (Fixed in #7991)
* [ ] The test in `TestWriteInteraction` calls private `ProcessWriteResponseMessage` instead of calling the public `OnMessageReceived` API.  As a result we are not properly testing the lifetime handling.
* [ ] WriteClient::ProcessAttributeStatusElement reads node ids from the attribute path TLV. This doesn't make sense to me: For a WriteResponse message the node for all paths should be clear from the packet headers and should not be present in the TLV at all. If it is thus present in the spec, that's a bug in the spec that should be filed and we should implement the sane thing.  Tracked in #7971
* [ ] WriteHandler::ProcessAttributeDataList likewise reads node ids from the TLV. This does not make sense: writes are always targeted at the message recipient node (and the node id may not even be known, if the write is issued to a group).  Tracked in #7972
* [x] Why is `WriteClient::FinalizeMessage` public API?  It shouldn't be; it's an internal helper method.
* [x] The API contract for `WriteClient` is not documented.  Is the intent that you call allocate one, then call `PrepareAttribute` followed by `FinishAttribute` for every attribute you want to read (why the separate `FinishAttribute`; that's not documented), then call `SendWriteRequest`?  Or something else?  Needs to be documented clearly.
* [ ] I assume the lack of group/wildcard writes is intentional for now. That's fine, but there should be a TODO comment indicating that it still needs to happen, no?  Tracked in #7973
* [ ] There's a WriteClient::GetAttributeDataElementTLVWriter API that is not very user-friendly. We should have a followup to figure out how to do this better, at least in common cases. We might need to fall back to exposing a TLVWriter for very complicated write requests, but a typical consumer writing something simple should not have to deal with a TLVWriter at all.  Tracked in #7974
* [x] `WriteHandler::OnWriteRequest` API documentation talks about shutdown being called "including if OnWriteHandler returns an error."  What is "OnWriteHandler" here?  Does it mean "OnWriteRequest"?
* [ ] Why is `WriteHandler::SendWriteResponse` (the one-arg version) public API?  If it needs to be public, why is it not documented?
* [x] Our general convention now seems to be to pass packetbuffers by rvalue reference, but a lot of this new code is passing them by value.  Is that intentional?

 #### Proposed Solution
Address the above issues.

@yunhanw-google @andy31415 @woody-apple

**Comment by yunhanw-google** [comment]
sure, would address them, thanks
